export interface EstateProject {
  work: string
  estate: string
  block: string
  hectares: string
}

export const ESTATE_PROJECTS: EstateProject[] = [
  { work: 'HARVESTING', estate: 'Ladang Sungai Papan', block: 'P04', hectares: '197.81' },
  { work: 'HARVESTING', estate: 'Ladang Sungai Papan', block: 'P06', hectares: '230.11' },
  { work: 'HARVESTING', estate: 'Ladang Sungai Papan', block: 'P10', hectares: '203.24' },
  { work: 'HARVESTING', estate: 'Ladang Sungai Papan', block: 'P11', hectares: '166.29' },
  { work: 'HARVESTING', estate: 'Ladang Sungai Papan', block: 'P12', hectares: '110.83' },
  { work: 'HARVESTING', estate: 'Ladang Sungai Papan', block: 'P13', hectares: '164.13' },
  { work: 'HARVESTING', estate: 'Ladang Sungai Papan', block: 'P16', hectares: '167.86' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P11', hectares: '166.29' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P12', hectares: '110.83' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P13', hectares: '164.13' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P14', hectares: '167.86' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P15', hectares: '136.57' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P16', hectares: '221.12' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P06', hectares: '230.11' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P07', hectares: '106.88' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P08', hectares: '239.12' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P03', hectares: '246.41' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P04', hectares: '197.81' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sungai Papan', block: 'P10', hectares: '203.24' },
  { work: 'HIRING OF JCB', estate: 'Ladang Sungai Papan', block: 'JCB', hectares: 'N/A' },
  { work: 'TRANSPORT', estate: 'Ladang Bukit Layang', block: 'P00/01', hectares: '44.54' },
  { work: 'TRANSPORT', estate: 'Ladang Bukit Layang', block: 'P00/02', hectares: '43.17' },
  { work: 'TRANSPORT', estate: 'Ladang Bukit Layang', block: 'P00/03', hectares: '66.31' },
  { work: 'TRANSPORT', estate: 'Ladang Bukit Layang', block: 'P03/01', hectares: '61.95' },
  { work: 'TRANSPORT', estate: 'Ladang Bukit Layang', block: 'P03/02', hectares: '88.53' },
  { work: 'TRANSPORTING', estate: 'Ladang Pasir Panjang', block: 'P90', hectares: '430.07' },
  { work: 'TRANSPORTING', estate: 'Ladang Pasir Panjang', block: 'P91', hectares: '77.31' },
  { work: 'TRANSPORTING', estate: 'Ladang Pasir Panjang', block: 'P92', hectares: '249.2' },
  { work: 'TRANSPORTING', estate: 'Ladang Pasir Panjang', block: 'P11', hectares: '130.25' },
  { work: 'TRANSPORTING', estate: 'Ladang Pasir Panjang', block: 'P12', hectares: '125.33' },
  { work: 'TRANSPORTING', estate: 'Ladang Pasir Panjang', block: 'P13', hectares: '232.36' },
  { work: 'TRANSPORTING', estate: 'Ladang Pasir Panjang', block: 'P14', hectares: '212.22' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P06', hectares: '244.5' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P07', hectares: '220.79' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P08', hectares: '229.45' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P09', hectares: '238.57' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P11M', hectares: '270.32' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P12M', hectares: '231.26' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P13M', hectares: '267.17' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P14M', hectares: '242.88' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P15', hectares: '110.43' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P16AI', hectares: '176.56' },
  { work: 'TRANSPORTING', estate: 'Ladang Tunjuk Laut', block: 'P16BI', hectares: '416.86' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P03', hectares: '192.95' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P04', hectares: '257.43' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P05', hectares: '251.53' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P06', hectares: '401.25' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P07', hectares: '342.97' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P08', hectares: '275.22' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P09', hectares: '327.6' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P10', hectares: '425.13' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P11', hectares: '225.2' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P12', hectares: '239.46' },
  { work: 'TRANSPORTING', estate: 'Ladang Siang', block: 'P99', hectares: '198.58' },
  { work: 'HARVESTING', estate: 'Ladang Siang', block: 'P05', hectares: '251.53' },
  { work: 'HARVESTING', estate: 'Ladang Siang', block: 'P06', hectares: '401.25' },
  { work: 'HARVESTING', estate: 'Ladang Siang', block: 'P08', hectares: '275.22' },
  { work: 'HIRING OF JCB', estate: 'Ladang Siang', block: 'JCB', hectares: 'N/A' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Palong', block: 'P07', hectares: '195.36' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Palong', block: 'P08', hectares: '186.79' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Palong', block: 'P09', hectares: '233.69' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Palong', block: 'P10', hectares: '202.36' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Palong', block: 'P11', hectares: '168.15' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Palong', block: 'P12', hectares: '432.2' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Palong', block: 'P13', hectares: '411.34' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'POO', hectares: '94.25' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P01', hectares: '336.1' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P04', hectares: '23.83' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P04A', hectares: '157.62' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P05', hectares: '153.74' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P06', hectares: '196.75' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P07', hectares: '188.81' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P08', hectares: '149.31' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P09', hectares: '193.91' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P10', hectares: '115.9' },
  { work: 'MTG BIN SISTEM - TRANSPORT', estate: 'Ladang Sedenak', block: 'P17', hectares: '152.15' },
  { work: 'MTG BIN SISTEM-TRANSPORT', estate: 'Ladang Umac', block: 'P03', hectares: '298.89' },
  { work: 'MTG BIN SISTEM-TRANSPORT', estate: 'Ladang Umac', block: 'P04', hectares: '241.26' },
  { work: 'MTG BIN SISTEM-TRANSPORT', estate: 'Ladang Umac', block: 'P05', hectares: '235.55' },
  { work: 'MTG BIN SISTEM-TRANSPORT', estate: 'Ladang Umac', block: 'P06', hectares: '272.86' },
  { work: 'MTG BIN SISTEM-TRANSPORT', estate: 'Ladang Umac', block: 'P07', hectares: '146.93' },
  { work: 'MTG BIN SISTEM-TRANSPORT', estate: 'Ladang Umac', block: 'P08', hectares: '157.76' },
  { work: 'MTG BIN SISTEM-TRANSPORT', estate: 'Ladang Umac', block: 'P09', hectares: '173.89' },
  { work: 'MTG BIN SISTEM-TRANSPORT', estate: 'Ladang Umac', block: 'P21', hectares: '28.86' },
  { work: 'HARVESTING', estate: 'Ladang Selai (Enggang Division)', block: 'FIELD 10E', hectares: '200.32' },
  { work: 'HARVESTING', estate: 'Ladang Selai (Enggang Division)', block: 'FIELD 12E', hectares: '197.77' },
  { work: 'HARVESTING', estate: 'Ladang Selai (Enggang Division)', block: 'FIELD 13E', hectares: '215.99' },
  { work: 'HARVESTING', estate: 'Ladang Selai (Enggang Division)', block: '14E', hectares: '207.58' },
  { work: 'LOADING / TRANSPORTING', estate: 'Ladang Air Manis', block: 'P95', hectares: '263.98' },
  { work: 'LOADING / TRANSPORTING', estate: 'Ladang Air Manis', block: 'P04', hectares: '221.37' },
  { work: 'LOADING / TRANSPORTING', estate: 'Ladang Air Manis', block: 'P07', hectares: '119.82' },
  { work: 'LOADING / TRANSPORTING', estate: 'Ladang Air Manis', block: 'P11', hectares: '213.4' },
  { work: 'HARVESTING', estate: 'Ladang Air Manis', block: 'P04', hectares: '221.37' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P03', hectares: '160.93' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P04', hectares: '168.96' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P05', hectares: '136.12' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P06', hectares: '194.6' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P07', hectares: '202.27' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P08', hectares: '228.65' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P09', hectares: '249.39' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P10', hectares: '292.37' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P11', hectares: '217.41' },
  { work: 'MTG BIN SYSTEM - TRANSPORT', estate: 'Ladang Pasir Logok', block: 'P20', hectares: '140.91' },
  { work: 'HARVESTING', estate: 'Ladang Pasir Logok', block: 'P11', hectares: '217.41' },
  { work: 'HARVESTING', estate: 'Ladang Basir Ismail', block: 'P11', hectares: '71.62' },
]
